//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Web;
    
    public partial class user
    {
        [DisplayName("Registration ID")]
        public int regId { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "This field is required.")]
        public string fname { get; set; }

        [DisplayName("Last Name")]
        [Required(ErrorMessage = "This field is required.")]
        public string lname { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "This field is required.")]
        public string email { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required.")]
        public string password_ { get; set; }

        [DisplayName("Age")]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<int> age { get; set; }

        [DisplayName("Occupation")]
        [Required(ErrorMessage = "This field is required.")]
        public string ocp { get; set; }

        [DisplayName("Weight")]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<int> weight_ { get; set; }

        [DisplayName("Height")]
        [Required(ErrorMessage = "This field is required.")]
        public Nullable<float> height { get; set; }

        [DisplayName("Contact No")]
        [Required(ErrorMessage = "This field is required.")]
        public string phone { get; set; }

        [DisplayName("Address")]
        [Required(ErrorMessage = "This field is required.")]
        public string address { get; set; }

        [DisplayName("Shedule")]
        [Required(ErrorMessage = "This field is required.")]
        public string shedule { get; set; }

        [DisplayName("Dietery Plan")]
        [Required(ErrorMessage = "This field is required.")]
        public string d_plan { get; set; }

        [DisplayName("Payment Method")]
        [Required(ErrorMessage = "This field is required.")]
        public string pay_type { get; set; }

        [DisplayName("Gender")]
        [Required(ErrorMessage = "This field is required.")]
        public string gender { get; set; }

        [DisplayName("Upload Profile Picture")]
        public string img_path { get; set; }

        public bool showPass { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }
    }
}
